version: 2
updates:
- package-ecosystem: gradle
  directory: "/annotation-file-utilities"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.errorprone:javac
    versions:
    - 1.8.0-u20
